editor: code
resolve_path: /home/username/projects/dependencies
project_paths:
      - /home/putak/steinwurf/dummynet/dummynet
release_email:
      host: smtp.emailhost.com
      port: 587
      sender: marko@steinwurf.com
      password: N/384451170550ur
      receiver: release_email_receiver@email.com

tailscale:
      api_key: tskey-123456789
      url: <tailscale api URL, something like: https://api.tailscale.com/api/v2/tailnet/{user}>
      credentials:
            user: common_account_name
            password: common_account_password
github_token: <your_PAT_here>