name: Waf Python Tests
"on":
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
  pull_request:
jobs:
  waf:
    name: Waf
    runs-on:
      - self-hosted
      - vm
      - ubuntu-current
    strategy:
      matrix:
        container:
          - python:3.11
          - python:3.13
    container:
      image: "${{ matrix.container }}"
      options: >-
        --user 0:0
        --cap-add=NET_ADMIN
        --device /dev/net/tun
        --cgroupns=host
    steps:
      - name: Install dependencies
        run: apt update && apt install -y sudo
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: python3 waf configure
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: [self-hosted, vm, ubuntu-current]
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
