name: Waf Python Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  waf:
    name: Waf
    runs-on: [self-hosted, builder, docker]
    container:
      image: ghcr.io/steinwurf/python-bindings:latest
      options: --user 0:0 --privileged
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: python3 waf configure
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests
